// Generated by tools/generate-operator.mjs from the reviewed public contract.
import Foundation

extension OperatorClient {
    /// GET /v1/operator/capabilities
    public func capabilities(query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/capabilities", query: query)
    }
    /// GET /v1/operator/health
    public func health(query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/health", query: query)
    }
    /// GET /v1/operator/merchants
    public func listMerchants(query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants", query: query)
    }
    /// POST /v1/operator/merchants
    public func createMerchant(body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants", body: body, idempotencyKey: idempotencyKey)
    }
    /// GET /v1/operator/merchants/{merchant_id}
    public func getMerchant(merchantID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())", query: query)
    }
    /// POST /v1/operator/merchants/{merchant_id}
    public func updateMerchant(merchantID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())", body: body, idempotencyKey: idempotencyKey)
    }
    /// GET /v1/operator/merchants/{merchant_id}/users
    public func listUsers(merchantID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/users", query: query)
    }
    /// POST /v1/operator/merchants/{merchant_id}/users
    public func createUser(merchantID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/users", body: body, idempotencyKey: idempotencyKey)
    }
    /// GET /v1/operator/merchants/{merchant_id}/users/{user_id}
    public func getUser(merchantID: UUID, userID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/users/\(userID.uuidString.lowercased())", query: query)
    }
    /// POST /v1/operator/merchants/{merchant_id}/users/{user_id}
    public func updateUser(merchantID: UUID, userID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/users/\(userID.uuidString.lowercased())", body: body, idempotencyKey: idempotencyKey)
    }
    /// POST /v1/operator/merchants/{merchant_id}/users/{user_id}/password
    public func setUserPassword(merchantID: UUID, userID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/users/\(userID.uuidString.lowercased())/password", body: body, idempotencyKey: idempotencyKey)
    }
    /// POST /v1/operator/merchants/{merchant_id}/users/{user_id}/revoke-sessions
    public func revokeUserSessions(merchantID: UUID, userID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/users/\(userID.uuidString.lowercased())/revoke-sessions", body: body, idempotencyKey: idempotencyKey)
    }
    /// GET /v1/operator/merchants/{merchant_id}/invitations
    public func listInvitations(merchantID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/invitations", query: query)
    }
    /// POST /v1/operator/merchants/{merchant_id}/invitations
    public func createInvitation(merchantID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/invitations", body: body, idempotencyKey: idempotencyKey)
    }
    /// GET /v1/operator/invitations/{invitation_id}
    public func getInvitation(invitationID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/invitations/\(invitationID.uuidString.lowercased())", query: query)
    }
    /// POST /v1/operator/invitations/{invitation_id}/resend
    public func resendInvitation(invitationID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/invitations/\(invitationID.uuidString.lowercased())/resend", body: body, idempotencyKey: idempotencyKey)
    }
    /// POST /v1/operator/invitations/{invitation_id}/revoke
    public func revokeInvitation(invitationID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/invitations/\(invitationID.uuidString.lowercased())/revoke", body: body, idempotencyKey: idempotencyKey)
    }
    /// GET /v1/operator/merchants/{merchant_id}/credits
    public func getCredits(merchantID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/credits", query: query)
    }
    /// GET /v1/operator/merchants/{merchant_id}/credits/ledger
    public func listCreditLedger(merchantID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/credits/ledger", query: query)
    }
    /// POST /v1/operator/merchants/{merchant_id}/credits/adjustments
    public func adjustCredits(merchantID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/credits/adjustments", body: body, idempotencyKey: idempotencyKey)
    }
    /// GET /v1/operator/merchants/{merchant_id}/topups
    public func listTopups(merchantID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/topups", query: query)
    }
    /// POST /v1/operator/merchants/{merchant_id}/topups
    public func createTopup(merchantID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/topups", body: body, idempotencyKey: idempotencyKey)
    }
    /// GET /v1/operator/merchants/{merchant_id}/topups/{topup_id}
    public func getTopup(merchantID: UUID, topupID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/topups/\(topupID.uuidString.lowercased())", query: query)
    }
    /// GET /v1/operator/reports
    public func reports(query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/reports", query: query)
    }
    /// GET /v1/operator/audit
    public func listAudit(query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/audit", query: query)
    }
    /// GET /v1/operator/events
    public func listEvents(query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/events", query: query)
    }
    /// GET /v1/operator/webhooks
    public func listWebhooks(query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/webhooks", query: query)
    }
    /// POST /v1/operator/webhooks
    public func createWebhook(body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/webhooks", body: body, idempotencyKey: idempotencyKey)
    }
    /// POST /v1/operator/webhooks/{webhook_id}
    public func updateWebhook(webhookID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/webhooks/\(webhookID.uuidString.lowercased())", body: body, idempotencyKey: idempotencyKey)
    }
    /// POST /v1/operator/webhooks/{webhook_id}/rotate
    public func rotateWebhookSecret(webhookID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/webhooks/\(webhookID.uuidString.lowercased())/rotate", body: body, idempotencyKey: idempotencyKey)
    }
    /// GET /v1/operator/webhooks/{webhook_id}/deliveries
    public func listWebhookDeliveries(webhookID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/webhooks/\(webhookID.uuidString.lowercased())/deliveries", query: query)
    }
    /// GET /v1/operator/merchants/{merchant_id}/projects
    public func listProjects(merchantID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects", query: query)
    }
    /// POST /v1/operator/merchants/{merchant_id}/projects
    public func createProject(merchantID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects", body: body, idempotencyKey: idempotencyKey)
    }
    /// GET /v1/operator/merchants/{merchant_id}/projects/{project_id}
    public func getProject(merchantID: UUID, projectID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects/\(projectID.uuidString.lowercased())", query: query)
    }
    /// POST /v1/operator/merchants/{merchant_id}/projects/{project_id}
    public func updateProject(merchantID: UUID, projectID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects/\(projectID.uuidString.lowercased())", body: body, idempotencyKey: idempotencyKey)
    }
    /// GET /v1/operator/merchants/{merchant_id}/projects/{project_id}/stores
    public func listStores(merchantID: UUID, projectID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects/\(projectID.uuidString.lowercased())/stores", query: query)
    }
    /// POST /v1/operator/merchants/{merchant_id}/projects/{project_id}/stores
    public func createStore(merchantID: UUID, projectID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects/\(projectID.uuidString.lowercased())/stores", body: body, idempotencyKey: idempotencyKey)
    }
    /// GET /v1/operator/merchants/{merchant_id}/projects/{project_id}/stores/{store_id}
    public func getStore(merchantID: UUID, projectID: UUID, storeID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects/\(projectID.uuidString.lowercased())/stores/\(storeID.uuidString.lowercased())", query: query)
    }
    /// POST /v1/operator/merchants/{merchant_id}/projects/{project_id}/stores/{store_id}
    public func updateStore(merchantID: UUID, projectID: UUID, storeID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects/\(projectID.uuidString.lowercased())/stores/\(storeID.uuidString.lowercased())", body: body, idempotencyKey: idempotencyKey)
    }
    /// GET /v1/operator/merchants/{merchant_id}/projects/{project_id}/stores/{store_id}/checkout-appearance
    public func getStoreAppearance(merchantID: UUID, projectID: UUID, storeID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects/\(projectID.uuidString.lowercased())/stores/\(storeID.uuidString.lowercased())/checkout-appearance", query: query)
    }
    /// POST /v1/operator/merchants/{merchant_id}/projects/{project_id}/stores/{store_id}/checkout-appearance
    public func updateStoreAppearance(merchantID: UUID, projectID: UUID, storeID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects/\(projectID.uuidString.lowercased())/stores/\(storeID.uuidString.lowercased())/checkout-appearance", body: body, idempotencyKey: idempotencyKey)
    }
    /// GET /v1/operator/merchants/{merchant_id}/projects/{project_id}/stores/{store_id}/payment-assets
    public func listStorePaymentAssets(merchantID: UUID, projectID: UUID, storeID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects/\(projectID.uuidString.lowercased())/stores/\(storeID.uuidString.lowercased())/payment-assets", query: query)
    }
    /// POST /v1/operator/merchants/{merchant_id}/projects/{project_id}/stores/{store_id}/payment-assets
    public func updateStorePaymentAssets(merchantID: UUID, projectID: UUID, storeID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects/\(projectID.uuidString.lowercased())/stores/\(storeID.uuidString.lowercased())/payment-assets", body: body, idempotencyKey: idempotencyKey)
    }
    /// GET /v1/operator/merchants/{merchant_id}/projects/{project_id}/stores/{store_id}/webhooks
    public func listStoreWebhooks(merchantID: UUID, projectID: UUID, storeID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects/\(projectID.uuidString.lowercased())/stores/\(storeID.uuidString.lowercased())/webhooks", query: query)
    }
    /// POST /v1/operator/merchants/{merchant_id}/projects/{project_id}/stores/{store_id}/webhooks
    public func createStoreWebhook(merchantID: UUID, projectID: UUID, storeID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects/\(projectID.uuidString.lowercased())/stores/\(storeID.uuidString.lowercased())/webhooks", body: body, idempotencyKey: idempotencyKey)
    }
    /// POST /v1/operator/merchants/{merchant_id}/projects/{project_id}/stores/{store_id}/webhooks/{webhook_id}
    public func updateStoreWebhook(merchantID: UUID, projectID: UUID, storeID: UUID, webhookID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects/\(projectID.uuidString.lowercased())/stores/\(storeID.uuidString.lowercased())/webhooks/\(webhookID.uuidString.lowercased())", body: body, idempotencyKey: idempotencyKey)
    }
    /// GET /v1/operator/merchants/{merchant_id}/projects/{project_id}/invoices
    public func listInvoices(merchantID: UUID, projectID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects/\(projectID.uuidString.lowercased())/invoices", query: query)
    }
    /// GET /v1/operator/merchants/{merchant_id}/projects/{project_id}/invoices/{invoice_id}
    public func getInvoice(merchantID: UUID, projectID: UUID, invoiceID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects/\(projectID.uuidString.lowercased())/invoices/\(invoiceID.uuidString.lowercased())", query: query)
    }
    /// GET /v1/operator/merchants/{merchant_id}/projects/{project_id}/wallets
    public func listWallets(merchantID: UUID, projectID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects/\(projectID.uuidString.lowercased())/wallets", query: query)
    }
    /// GET /v1/operator/merchants/{merchant_id}/projects/{project_id}/wallets/{wallet_id}/addresses
    public func listWalletAddresses(merchantID: UUID, projectID: UUID, walletID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/projects/\(projectID.uuidString.lowercased())/wallets/\(walletID.uuidString.lowercased())/addresses", query: query)
    }
    /// GET /v1/operator/merchants/{merchant_id}/api-credentials
    public func listMerchantCredentials(merchantID: UUID, query: [String: String] = [:]) async throws -> APIResponse {
        try await http.request("GET", "/v1/operator/merchants/\(merchantID.uuidString.lowercased())/api-credentials", query: query)
    }
    /// POST /v1/operator/merchants/{merchant_id}/api-credentials
    public func createMerchantCredential(merchantID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/api-credentials", body: body, idempotencyKey: idempotencyKey)
    }
    /// POST /v1/operator/merchants/{merchant_id}/api-credentials/{credential_id}
    public func updateMerchantCredential(merchantID: UUID, credentialID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/api-credentials/\(credentialID.uuidString.lowercased())", body: body, idempotencyKey: idempotencyKey)
    }
    /// POST /v1/operator/merchants/{merchant_id}/api-credentials/{credential_id}/rotate
    public func rotateMerchantCredential(merchantID: UUID, credentialID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/api-credentials/\(credentialID.uuidString.lowercased())/rotate", body: body, idempotencyKey: idempotencyKey)
    }
    /// POST /v1/operator/merchants/{merchant_id}/api-credentials/{credential_id}/revoke
    public func revokeMerchantCredential(merchantID: UUID, credentialID: UUID, body: [String: JSONValue], idempotencyKey: String) async throws -> APIResponse {
        try await write("/v1/operator/merchants/\(merchantID.uuidString.lowercased())/api-credentials/\(credentialID.uuidString.lowercased())/revoke", body: body, idempotencyKey: idempotencyKey)
    }
}
